//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vanzari
    {
        public int Id { get; set; }
        public Nullable<int> ProdusId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public Nullable<int> AngajatId { get; set; }
    }
}
