//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weather_Aplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Weather_Aplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _ {
            get {
                object obj = ResourceManager.GetObject("_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _return {
            get {
                object obj = ResourceManager.GetObject("_return", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon app_icon {
            get {
                object obj = ResourceManager.GetObject("app_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap app_icon1 {
            get {
                object obj = ResourceManager.GetObject("app_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_evening {
            get {
                object obj = ResourceManager.GetObject("bg_evening", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_morning {
            get {
                object obj = ResourceManager.GetObject("bg_morning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amsterdam
        ///Ankara
        ///Athens
        ///Belgrade
        ///Berlin
        ///Bratislava
        ///Brussels
        ///Bucharest
        ///Budapest
        ///Copenhagen
        ///Dublin Airport
        ///Helsinki
        ///Kiev
        ///Chisinau
        ///Lisbon
        ///Ljubljana
        ///London
        ///Luxembourg
        ///Madrid
        ///Malta
        ///Minsk
        ///Moscow
        ///Oslo
        ///Paris
        ///Podgorica
        ///Praha-Libus
        ///Pratica Di Mare
        ///Reykjavik
        ///Riga
        ///Sarajevo-Bejelave
        ///Skopje
        ///Sofia
        ///Stockholm
        ///Tallinn
        ///Tirana
        ///Vaduz
        ///Vienna
        ///Vilnius
        ///Warsaw
        ///Zagreb / Maksimir.
        /// </summary>
        internal static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_d {
            get {
                object obj = ResourceManager.GetObject("clear_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_day {
            get {
                object obj = ResourceManager.GetObject("clear_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_n {
            get {
                object obj = ResourceManager.GetObject("clear_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap clear_night {
            get {
                object obj = ResourceManager.GetObject("clear_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_d {
            get {
                object obj = ResourceManager.GetObject("cloudy_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cloudy_n {
            get {
                object obj = ResourceManager.GetObject("cloudy_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_clear_day {
            get {
                object obj = ResourceManager.GetObject("ds_clear_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_clear_night {
            get {
                object obj = ResourceManager.GetObject("ds_clear_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_dust_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_dust_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fair_day {
            get {
                object obj = ResourceManager.GetObject("ds_fair_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fair_night {
            get {
                object obj = ResourceManager.GetObject("ds_fair_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_flurries_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_flurries_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_fog_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_moon_night {
            get {
                object obj = ResourceManager.GetObject("ds_fog_moon_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_fog_sun_day {
            get {
                object obj = ResourceManager.GetObject("ds_fog_sun_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_freezing_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_freezing_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_hail_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_hail_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_haze_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_haze_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_heavy_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_heavy_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_heavy_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_heavy_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_hurricane_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_hurricane_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_light_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_light_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_mostly_cloudy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_mostly_cloudy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_partly_cloudy_day {
            get {
                object obj = ResourceManager.GetObject("ds_partly_cloudy_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_partly_cloudy_night {
            get {
                object obj = ResourceManager.GetObject("ds_partly_cloudy_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scattered_showers_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_scattered_showers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scattered_thundershowers_night {
            get {
                object obj = ResourceManager.GetObject("ds_scattered_thundershowers_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_scatttered_thundershowers_day {
            get {
                object obj = ResourceManager.GetObject("ds_scatttered_thundershowers_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_sleet_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_sleet_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_smoky_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_smoky_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_snow_rain_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_snow_rain_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_thundershowers_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_thundershowers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_tornado_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_tornado_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ds_windy_day_night {
            get {
                object obj = ResourceManager.GetObject("ds_windy_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap dust_day_night {
            get {
                object obj = ResourceManager.GetObject("dust_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fair_day {
            get {
                object obj = ResourceManager.GetObject("fair_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fair_night {
            get {
                object obj = ResourceManager.GetObject("fair_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap flurries_day_night {
            get {
                object obj = ResourceManager.GetObject("flurries_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_day_night {
            get {
                object obj = ResourceManager.GetObject("fog_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_moon_night {
            get {
                object obj = ResourceManager.GetObject("fog_moon_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap fog_sun_day {
            get {
                object obj = ResourceManager.GetObject("fog_sun_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foggy_d {
            get {
                object obj = ResourceManager.GetObject("foggy_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap foggy_n {
            get {
                object obj = ResourceManager.GetObject("foggy_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap freezing_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("freezing_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///44
        ///16.07.2017
        ///Sunday
        ///4:46
        ///19:57
        ///cloudy
        ///22
        ///17
        ///E
        ///7.2
        ///17.07.2017
        ///Monday
        ///4:47
        ///19:56
        ///prevailingly cloudy
        ///24
        ///17
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:48
        ///19:56
        ///partly cloudy
        ///28
        ///16
        ///NE
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///4:49
        ///19:55
        ///mostly clear
        ///30
        ///16
        ///N
        ///7.2
        ///.
        /// </summary>
        internal static string Get_Data_For_App {
            get {
                return ResourceManager.GetString("Get_Data_For_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///96
        ///16.07.2017
        ///Sunday
        ///5:39
        ///21:55
        ///cloudy
        ///21
        ///16
        ///W
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:40
        ///21:53
        ///prevailingly cloudy
        ///21
        ///14
        ///NW
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:41
        ///21:52
        ///partly cloudy
        ///24
        ///12
        ///E
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:43
        ///21:51
        ///partly cloudy
        ///31
        ///17
        ///SE
        ///25.2
        ///20.07.2017
        ///Thursday
        ///5:44
        ///21:50
        ///prevailingly cloudy
        ///22
        ///18
        ///SW
        ///14.4
        ///Amsterdam.
        /// </summary>
        internal static string Get_Data_For_App_Amsterdam {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Amsterdam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27
        ///51
        ///16.07.2017
        ///Sunday
        ///4:32
        ///19:16
        ///mostly clear
        ///32
        ///17
        ///S
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:33
        ///19:15
        ///mostly clear
        ///33
        ///18
        ///SE
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///4:34
        ///19:14
        ///mostly clear
        ///32
        ///18
        ///W
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:35
        ///19:14
        ///mostly clear
        ///26
        ///17
        ///NW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:36
        ///19:13
        ///prevailingly cloudy
        ///26
        ///16
        ///N
        ///7.2
        ///Ankara.
        /// </summary>
        internal static string Get_Data_For_App_Ankara {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Ankara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///32
        ///16.07.2017
        ///Sunday
        ///5:16
        ///19:46
        ///mostly clear
        ///31
        ///24
        ///N
        ///3.6
        ///17.07.2017
        ///Monday
        ///5:16
        ///19:46
        ///partly cloudy
        ///26
        ///22
        ///NW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:17
        ///19:45
        ///mostly clear
        ///27
        ///20
        ///N
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///5:18
        ///19:45
        ///clear
        ///29
        ///22
        ///N
        ///25.2
        ///20.07.2017
        ///Thursday
        ///5:19
        ///19:44
        ///clear
        ///30
        ///23
        ///N
        ///25.2
        ///Athens.
        /// </summary>
        internal static string Get_Data_For_App_Athens {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Athens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///71
        ///16.07.2017
        ///Sunday
        ///5:07
        ///20:21
        ///mostly clear
        ///24
        ///15
        ///N
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:08
        ///20:20
        ///mostly clear
        ///27
        ///15
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:09
        ///20:19
        ///clear
        ///30
        ///17
        ///NE
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///5:10
        ///20:18
        ///clear
        ///32
        ///18
        ///NE
        ///7.2
        ///20.07.2017
        ///Thursday
        ///5:11
        ///20:17
        ///clear
        ///34
        ///21
        ///E
        ///7.2
        ///Belgrade.
        /// </summary>
        internal static string Get_Data_For_App_Belgrade {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Belgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///80
        ///16.07.2017
        ///Sunday
        ///5:03
        ///21:21
        ///prevailingly cloudy
        ///20
        ///12
        ///SW
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:05
        ///21:20
        ///prevailingly cloudy
        ///20
        ///17
        ///NW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:06
        ///21:19
        ///prevailingly cloudy
        ///23
        ///11
        ///N
        ///0.7200000000000001
        ///19.07.2017
        ///Wednesday
        ///5:07
        ///21:17
        ///partly cloudy
        ///27
        ///13
        ///E
        ///7.2
        ///20.07.2017
        ///Thursday
        ///5:09
        ///21:16
        ///cloudy
        ///30
        ///18
        ///S
        ///14.4
        ///Berlin.
        /// </summary>
        internal static string Get_Data_For_App_Berlin {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Berlin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///62
        ///16.07.2017
        ///Sunday
        ///5:08
        ///20:46
        ///prevailingly cloudy
        ///25
        ///13
        ///N
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:09
        ///20:45
        ///mostly clear
        ///28
        ///14
        ///W
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:10
        ///20:44
        ///mostly clear
        ///30
        ///17
        ///S
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///5:11
        ///20:43
        ///prevailingly cloudy
        ///32
        ///18
        ///S
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:12
        ///20:42
        ///clear
        ///34
        ///19
        ///S
        ///7.2
        ///Bratislava.
        /// </summary>
        internal static string Get_Data_For_App_Bratislava {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Bratislava", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///92
        ///16.07.2017
        ///Sunday
        ///4:46
        ///19:57
        ///cloudy
        ///18
        ///16
        ///NE
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:47
        ///19:56
        ///prevailingly cloudy
        ///25
        ///16
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:48
        ///19:56
        ///partly cloudy
        ///27
        ///16
        ///NE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:49
        ///19:55
        ///mostly clear
        ///28
        ///16
        ///N
        ///7.2
        ///20.07.2017
        ///Thursday
        ///4:50
        ///19:54
        ///mostly clear
        ///29
        ///16
        ///N
        ///3.6
        ///Brussels.
        /// </summary>
        internal static string Get_Data_For_App_Brussels {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Brussels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///74
        ///16.07.2017
        ///Sunday
        ///5:03
        ///20:35
        ///mostly clear
        ///24
        ///13
        ///N
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:04
        ///20:34
        ///clear
        ///27
        ///13
        ///N
        ///3.6
        ///18.07.2017
        ///Tuesday
        ///5:05
        ///20:34
        ///mostly clear
        ///29
        ///16
        ///S
        ///3.6
        ///19.07.2017
        ///Wednesday
        ///5:06
        ///20:33
        ///mostly clear
        ///32
        ///17
        ///S
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:07
        ///20:32
        ///mostly clear
        ///34
        ///18
        ///S
        ///7.2
        ///Bucharest.
        /// </summary>
        internal static string Get_Data_For_App_Bucharest {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Bucharest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///87
        ///16.07.2017
        ///Sunday
        ///4:48
        ///21:42
        ///cloudy
        ///18
        ///14
        ///S
        ///32.4
        ///17.07.2017
        ///Monday
        ///4:50
        ///21:40
        ///partly cloudy
        ///18
        ///13
        ///W
        ///25.2
        ///18.07.2017
        ///Tuesday
        ///4:51
        ///21:39
        ///prevailingly cloudy
        ///18
        ///14
        ///W
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///4:53
        ///21:37
        ///mostly clear
        ///18
        ///14
        ///S
        ///7.2
        ///20.07.2017
        ///Thursday
        ///4:55
        ///21:36
        ///cloudy
        ///19
        ///16
        ///SE
        ///14.4
        ///Budapest.
        /// </summary>
        internal static string Get_Data_For_App_Budapest {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Budapest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26
        ///80
        ///16.07.2017
        ///Sunday
        ///7:25
        ///22:00
        ///clear
        ///28
        ///19
        ///SW
        ///14.4
        ///17.07.2017
        ///Monday
        ///7:25
        ///22:00
        ///mostly clear
        ///24
        ///18
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///7:26
        ///21:59
        ///partly cloudy
        ///25
        ///19
        ///NW
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///7:27
        ///21:58
        ///partly cloudy
        ///25
        ///18
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///7:28
        ///21:58
        ///partly cloudy
        ///23
        ///18
        ///N
        ///25.2
        ///Chisinau.
        /// </summary>
        internal static string Get_Data_For_App_Chisinau {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Chisinau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///93
        ///16.07.2017
        ///Sunday
        ///6:17
        ///22:44
        ///prevailingly cloudy
        ///19
        ///14
        ///W
        ///14.4
        ///17.07.2017
        ///Monday
        ///6:18
        ///22:43
        ///clear
        ///22
        ///10
        ///SW
        ///0.7200000000000001
        ///18.07.2017
        ///Tuesday
        ///6:20
        ///22:42
        ///mostly clear
        ///21
        ///12
        ///SE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///6:21
        ///22:41
        ///cloudy
        ///21
        ///15
        ///SE
        ///14.4
        ///20.07.2017
        ///Thursday
        ///6:22
        ///22:39
        ///prevailingly cloudy
        ///17
        ///10
        ///SW
        ///14.4
        ///Copenhagen.
        /// </summary>
        internal static string Get_Data_For_App_Copenhagen {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Copenhagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///52
        ///16.07.2017
        ///Sunday
        ///3:23
        ///21:28
        ///clear
        ///23
        ///9
        ///SW
        ///7.2
        ///17.07.2017
        ///Monday
        ///3:25
        ///21:26
        ///prevailingly cloudy
        ///19
        ///10
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///3:27
        ///21:24
        ///partly cloudy
        ///21
        ///9
        ///W
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///3:29
        ///21:22
        ///prevailingly cloudy
        ///18
        ///11
        ///NW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///3:31
        ///21:20
        ///partly cloudy
        ///19
        ///10
        ///NW
        ///14.4
        ///Dublin Airport.
        /// </summary>
        internal static string Get_Data_For_App_Dublin_Airport {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Dublin_Airport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///59
        ///16.07.2017
        ///Sunday
        ///4:05
        ///20:02
        ///mostly clear
        ///22
        ///11
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:06
        ///20:01
        ///partly cloudy
        ///24
        ///11
        ///W
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///4:07
        ///20:00
        ///prevailingly cloudy
        ///25
        ///13
        ///W
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:08
        ///19:59
        ///mostly clear
        ///25
        ///14
        ///N
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:09
        ///19:58
        ///mostly clear
        ///27
        ///14
        ///SE
        ///7.2
        ///Helsinki.
        /// </summary>
        internal static string Get_Data_For_App_Helsinki {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Helsinki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///56
        ///16.07.2017
        ///Sunday
        ///4:25
        ///19:55
        ///prevailingly cloudy
        ///24
        ///15
        ///N
        ///7.2
        ///17.07.2017
        ///Monday
        ///4:26
        ///19:54
        ///cloudy
        ///26
        ///17
        ///N
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///4:27
        ///19:53
        ///partly cloudy
        ///27
        ///14
        ///N
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:28
        ///19:52
        ///partly cloudy
        ///29
        ///16
        ///N
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:29
        ///19:51
        ///mostly clear
        ///30
        ///16
        ///N
        ///7.2
        ///Kiev.
        /// </summary>
        internal static string Get_Data_For_App_Kiev {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Kiev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///58
        ///16.07.2017
        ///Sunday
        ///5:27
        ///20:49
        ///partly cloudy
        ///24
        ///12
        ///NE
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:28
        ///20:48
        ///clear
        ///27
        ///11
        ///NE
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:29
        ///20:47
        ///clear
        ///30
        ///14
        ///E
        ///3.6
        ///19.07.2017
        ///Wednesday
        ///5:30
        ///20:46
        ///mostly clear
        ///32
        ///15
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:31
        ///20:45
        ///mostly clear
        ///33
        ///16
        ///W
        ///14.4
        ///Lisbon.
        /// </summary>
        internal static string Get_Data_For_App_Lisbon {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Lisbon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///85
        ///16.07.2017
        ///Sunday
        ///6:04
        ///22:11
        ///cloudy
        ///23
        ///18
        ///W
        ///14.4
        ///17.07.2017
        ///Monday
        ///6:05
        ///22:10
        ///partly cloudy
        ///23
        ///12
        ///NE
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///6:06
        ///22:09
        ///prevailingly cloudy
        ///24
        ///14
        ///E
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///6:08
        ///22:08
        ///cloudy
        ///24
        ///18
        ///S
        ///25.2
        ///20.07.2017
        ///Thursday
        ///6:09
        ///22:07
        ///partly cloudy
        ///21
        ///17
        ///W
        ///14.4
        ///Ljubljana.
        /// </summary>
        internal static string Get_Data_For_App_Ljubljana {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Ljubljana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///94
        ///16.07.2017
        ///Sunday
        ///5:46
        ///21:36
        ///cloudy
        ///23
        ///15
        ///W
        ///7.2
        ///17.07.2017
        ///Monday
        ///5:47
        ///21:35
        ///prevailingly cloudy
        ///24
        ///15
        ///NW
        ///3.6
        ///18.07.2017
        ///Tuesday
        ///5:48
        ///21:34
        ///prevailingly cloudy
        ///28
        ///16
        ///SE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:49
        ///21:33
        ///cloudy
        ///29
        ///18
        ///SW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:50
        ///21:32
        ///prevailingly cloudy
        ///23
        ///19
        ///SW
        ///14.4
        ///London.
        /// </summary>
        internal static string Get_Data_For_App_London {
            get {
                return ResourceManager.GetString("Get_Data_For_App_London", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35
        ///54
        ///16.07.2017
        ///Sunday
        ///6:58
        ///21:43
        ///clear
        ///37
        ///22
        ///S
        ///3.6
        ///17.07.2017
        ///Monday
        ///6:58
        ///21:42
        ///prevailingly cloudy
        ///37
        ///21
        ///S
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///6:59
        ///21:41
        ///partly cloudy
        ///36
        ///22
        ///SW
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///7:00
        ///21:41
        ///mostly clear
        ///32
        ///21
        ///SW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///7:01
        ///21:40
        ///prevailingly cloudy
        ///32
        ///20
        ///SW
        ///7.2
        ///Luxembourg.
        /// </summary>
        internal static string Get_Data_For_App_Luxembourg {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 27
        ///78
        ///16.07.2017
        ///Sunday
        ///5:58
        ///20:18
        ///mostly clear
        ///28
        ///25
        ///E
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:59
        ///20:18
        ///clear
        ///27
        ///24
        ///N
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:59
        ///20:17
        ///clear
        ///28
        ///25
        ///W
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///6:00
        ///20:16
        ///clear
        ///27
        ///25
        ///SW
        ///7.2
        ///20.07.2017
        ///Thursday
        ///6:01
        ///20:16
        ///clear
        ///27
        ///25
        ///S
        ///14.4
        ///Madrid.
        /// </summary>
        internal static string Get_Data_For_App_Madrid {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Madrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15
        ///73
        ///16.07.2017
        ///Sunday
        ///3:58
        ///20:32
        ///cloudy
        ///16
        ///11
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:00
        ///20:31
        ///prevailingly cloudy
        ///20
        ///12
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:01
        ///20:29
        ///prevailingly cloudy
        ///19
        ///11
        ///W
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:03
        ///20:28
        ///prevailingly cloudy
        ///20
        ///13
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:04
        ///20:27
        ///mostly clear
        ///22
        ///12
        ///W
        ///14.4
        ///Malta.
        /// </summary>
        internal static string Get_Data_For_App_Malta {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///70
        ///16.07.2017
        ///Sunday
        ///3:06
        ///20:01
        ///partly cloudy
        ///24
        ///18
        ///S
        ///25.2
        ///17.07.2017
        ///Monday
        ///3:08
        ///20:00
        ///prevailingly cloudy
        ///20
        ///13
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///3:09
        ///19:59
        ///partly cloudy
        ///21
        ///12
        ///SW
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///3:11
        ///19:57
        ///partly cloudy
        ///20
        ///12
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///3:12
        ///19:56
        ///partly cloudy
        ///20
        ///12
        ///W
        ///7.2
        ///Minsk.
        /// </summary>
        internal static string Get_Data_For_App_Minsk {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Minsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14
        ///96
        ///16.07.2017
        ///Sunday
        ///4:20
        ///22:23
        ///prevailingly cloudy
        ///19
        ///12
        ///S
        ///7.2
        ///17.07.2017
        ///Monday
        ///4:22
        ///22:21
        ///partly cloudy
        ///19
        ///9
        ///W
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:24
        ///22:19
        ///clear
        ///21
        ///11
        ///NW
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:26
        ///22:17
        ///mostly clear
        ///21
        ///9
        ///N
        ///3.6
        ///20.07.2017
        ///Thursday
        ///4:28
        ///22:15
        ///prevailingly cloudy
        ///24
        ///9
        ///S
        ///7.2
        ///Moscow.
        /// </summary>
        internal static string Get_Data_For_App_Moscow {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Moscow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24
        ///65
        ///16.07.2017
        ///Sunday
        ///6:05
        ///21:48
        ///prevailingly cloudy
        ///26
        ///17
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///6:06
        ///21:47
        ///prevailingly cloudy
        ///28
        ///16
        ///N
        ///3.6
        ///18.07.2017
        ///Tuesday
        ///6:07
        ///21:46
        ///prevailingly cloudy
        ///32
        ///18
        ///SE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///6:08
        ///21:45
        ///cloudy
        ///29
        ///21
        ///S
        ///14.4
        ///20.07.2017
        ///Thursday
        ///6:09
        ///21:44
        ///prevailingly cloudy
        ///23
        ///19
        ///W
        ///14.4
        ///Oslo.
        /// </summary>
        internal static string Get_Data_For_App_Oslo {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Oslo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 28
        ///38
        ///16.07.2017
        ///Sunday
        ///5:20
        ///20:17
        ///partly cloudy
        ///29
        ///21
        ///NE
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:21
        ///20:17
        ///mostly clear
        ///30
        ///18
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:22
        ///20:16
        ///clear
        ///32
        ///19
        ///S
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:23
        ///20:15
        ///clear
        ///34
        ///19
        ///S
        ///7.2
        ///20.07.2017
        ///Thursday
        ///5:24
        ///20:14
        ///mostly clear
        ///34
        ///20
        ///S
        ///7.2
        ///Paris.
        /// </summary>
        internal static string Get_Data_For_App_Paris {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Paris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///94
        ///16.07.2017
        ///Sunday
        ///5:11
        ///21:05
        ///prevailingly cloudy
        ///22
        ///11
        ///SW
        ///7.2
        ///17.07.2017
        ///Monday
        ///5:12
        ///21:04
        ///prevailingly cloudy
        ///23
        ///14
        ///NW
        ///3.6
        ///18.07.2017
        ///Tuesday
        ///5:13
        ///21:03
        ///prevailingly cloudy
        ///24
        ///15
        ///NE
        ///3.6
        ///19.07.2017
        ///Wednesday
        ///5:14
        ///21:02
        ///prevailingly cloudy
        ///29
        ///15
        ///W
        ///0.7200000000000001
        ///20.07.2017
        ///Thursday
        ///5:16
        ///21:01
        ///prevailingly cloudy
        ///32
        ///18
        ///S
        ///7.2
        ///Podgorica.
        /// </summary>
        internal static string Get_Data_For_App_Podgorica {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Podgorica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30
        ///32
        ///16.07.2017
        ///Sunday
        ///5:50
        ///20:42
        ///mostly clear
        ///30
        ///22
        ///NE
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:51
        ///20:42
        ///clear
        ///30
        ///20
        ///W
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:52
        ///20:41
        ///clear
        ///28
        ///23
        ///S
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:52
        ///20:40
        ///prevailingly cloudy
        ///28
        ///21
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:53
        ///20:40
        ///clear
        ///28
        ///21
        ///W
        ///14.4
        ///Praha-Libus.
        /// </summary>
        internal static string Get_Data_For_App_Praha_Libus {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Praha_Libus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10
        ///91
        ///16.07.2017
        ///Sunday
        ///5:45
        ///1:20
        ///prevailingly cloudy
        ///10
        ///7
        ///W
        ///25.2
        ///17.07.2017
        ///Monday
        ///5:48
        ///1:18
        ///cloudy
        ///11
        ///7
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:51
        ///1:15
        ///cloudy
        ///11
        ///10
        ///SE
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///5:54
        ///1:12
        ///cloudy
        ///12
        ///11
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:57
        ///1:09
        ///cloudy
        ///12
        ///8
        ///SE
        ///7.2
        ///Pratica Di Mare.
        /// </summary>
        internal static string Get_Data_For_App_Pratica_Di_Mare {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Pratica_Di_Mare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///82
        ///16.07.2017
        ///Sunday
        ///3:54
        ///21:05
        ///prevailingly cloudy
        ///19
        ///14
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///3:55
        ///21:03
        ///prevailingly cloudy
        ///20
        ///12
        ///W
        ///25.2
        ///18.07.2017
        ///Tuesday
        ///3:57
        ///21:02
        ///prevailingly cloudy
        ///19
        ///12
        ///W
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///3:59
        ///21:00
        ///prevailingly cloudy
        ///20
        ///12
        ///SW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:00
        ///20:59
        ///mostly clear
        ///21
        ///11
        ///NW
        ///3.6
        ///Reykjavik.
        /// </summary>
        internal static string Get_Data_For_App_Reykjavik {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Reykjavik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16
        ///79
        ///16.07.2017
        ///Sunday
        ///5:19
        ///20:25
        ///partly cloudy
        ///17
        ///10
        ///NE
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:20
        ///20:25
        ///clear
        ///22
        ///9
        ///NE
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:21
        ///20:24
        ///mostly clear
        ///25
        ///10
        ///NE
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///5:22
        ///20:23
        ///clear
        ///26
        ///12
        ///NW
        ///3.6
        ///20.07.2017
        ///Thursday
        ///5:22
        ///20:22
        ///mostly clear
        ///28
        ///16
        ///W
        ///3.6
        ///Riga.
        /// </summary>
        internal static string Get_Data_For_App_Riga {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Riga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20
        ///52
        ///16.07.2017
        ///Sunday
        ///5:12
        ///20:06
        ///cloudy
        ///20
        ///18
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:13
        ///20:06
        ///prevailingly cloudy
        ///25
        ///16
        ///N
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///5:14
        ///20:05
        ///prevailingly cloudy
        ///28
        ///16
        ///N
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:15
        ///20:04
        ///clear
        ///31
        ///15
        ///E
        ///0.7200000000000001
        ///20.07.2017
        ///Thursday
        ///5:16
        ///20:04
        ///mostly clear
        ///34
        ///18
        ///NE
        ///3.6
        ///Sarajevo-Bejelave.
        /// </summary>
        internal static string Get_Data_For_App_Sarajevo_Bejelave {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Sarajevo_Bejelave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 14
        ///73
        ///16.07.2017
        ///Sunday
        ///5:03
        ///20:02
        ///cloudy
        ///15
        ///14
        ///N
        ///7.2
        ///17.07.2017
        ///Monday
        ///5:04
        ///20:01
        ///prevailingly cloudy
        ///18
        ///12
        ///NE
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:05
        ///20:00
        ///mostly clear
        ///21
        ///14
        ///NE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:06
        ///20:00
        ///mostly clear
        ///24
        ///13
        ///NE
        ///7.2
        ///20.07.2017
        ///Thursday
        ///5:06
        ///19:59
        ///clear
        ///25
        ///14
        ///E
        ///7.2
        ///Skopje.
        /// </summary>
        internal static string Get_Data_For_App_Skopje {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Skopje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22
        ///72
        ///16.07.2017
        ///Sunday
        ///4:00
        ///21:48
        ///cloudy
        ///22
        ///12
        ///S
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:02
        ///21:46
        ///mostly clear
        ///21
        ///13
        ///W
        ///25.2
        ///18.07.2017
        ///Tuesday
        ///4:04
        ///21:44
        ///partly cloudy
        ///21
        ///12
        ///NW
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:06
        ///21:42
        ///mostly clear
        ///22
        ///12
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:08
        ///21:41
        ///partly cloudy
        ///22
        ///11
        ///E
        ///14.4
        ///Sofia.
        /// </summary>
        internal static string Get_Data_For_App_Sofia {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Sofia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///60
        ///16.07.2017
        ///Sunday
        ///3:35
        ///21:21
        ///clear
        ///21
        ///10
        ///NW
        ///7.2
        ///17.07.2017
        ///Monday
        ///3:37
        ///21:19
        ///prevailingly cloudy
        ///18
        ///11
        ///W
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///3:39
        ///21:17
        ///mostly clear
        ///20
        ///12
        ///W
        ///25.2
        ///19.07.2017
        ///Wednesday
        ///3:41
        ///21:16
        ///mostly clear
        ///18
        ///11
        ///NW
        ///25.2
        ///20.07.2017
        ///Thursday
        ///3:43
        ///21:14
        ///prevailingly cloudy
        ///18
        ///12
        ///W
        ///14.4
        ///Stockholm.
        /// </summary>
        internal static string Get_Data_For_App_Stockholm {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Stockholm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25
        ///57
        ///16.07.2017
        ///Sunday
        ///5:21
        ///20:12
        ///prevailingly cloudy
        ///27
        ///20
        ///NE
        ///7.2
        ///17.07.2017
        ///Monday
        ///5:22
        ///20:11
        ///prevailingly cloudy
        ///30
        ///17
        ///E
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:23
        ///20:11
        ///mostly clear
        ///30
        ///16
        ///NW
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///5:24
        ///20:10
        ///mostly clear
        ///31
        ///18
        ///NW
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:25
        ///20:09
        ///clear
        ///32
        ///20
        ///NW
        ///14.4
        ///Tallinn.
        /// </summary>
        internal static string Get_Data_For_App_Tallinn {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Tallinn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18
        ///74
        ///16.07.2017
        ///Sunday
        ///5:43
        ///21:13
        ///partly cloudy
        ///18
        ///10
        ///N
        ///7.2
        ///17.07.2017
        ///Monday
        ///5:44
        ///21:12
        ///partly cloudy
        ///22
        ///9
        ///N
        ///7.2
        ///18.07.2017
        ///Tuesday
        ///5:45
        ///21:11
        ///prevailingly cloudy
        ///24
        ///12
        ///N
        ///3.6
        ///19.07.2017
        ///Wednesday
        ///5:46
        ///21:10
        ///prevailingly cloudy
        ///26
        ///12
        ///S
        ///3.6
        ///20.07.2017
        ///Thursday
        ///5:47
        ///21:09
        ///cloudy
        ///22
        ///13
        ///N
        ///3.6
        ///Tirana.
        /// </summary>
        internal static string Get_Data_For_App_Tirana {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Tirana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23
        ///67
        ///16.07.2017
        ///Sunday
        ///5:11
        ///20:50
        ///partly cloudy
        ///24
        ///13
        ///N
        ///14.4
        ///17.07.2017
        ///Monday
        ///5:12
        ///20:49
        ///mostly clear
        ///27
        ///14
        ///NW
        ///3.6
        ///18.07.2017
        ///Tuesday
        ///5:13
        ///20:48
        ///mostly clear
        ///29
        ///16
        ///SE
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///5:14
        ///20:47
        ///partly cloudy
        ///32
        ///19
        ///S
        ///14.4
        ///20.07.2017
        ///Thursday
        ///5:15
        ///20:46
        ///mostly clear
        ///33
        ///19
        ///SE
        ///7.2
        ///Vaduz.
        /// </summary>
        internal static string Get_Data_For_App_Vaduz {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vaduz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19
        ///75
        ///16.07.2017
        ///Sunday
        ///4:05
        ///20:46
        ///cloudy
        ///19
        ///11
        ///NW
        ///14.4
        ///17.07.2017
        ///Monday
        ///4:06
        ///20:45
        ///prevailingly cloudy
        ///18
        ///11
        ///SW
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:07
        ///20:43
        ///prevailingly cloudy
        ///18
        ///10
        ///W
        ///14.4
        ///19.07.2017
        ///Wednesday
        ///4:09
        ///20:42
        ///prevailingly cloudy
        ///20
        ///11
        ///W
        ///14.4
        ///20.07.2017
        ///Thursday
        ///4:10
        ///20:41
        ///partly cloudy
        ///22
        ///10
        ///W
        ///7.2
        ///Vienna.
        /// </summary>
        internal static string Get_Data_For_App_Vienna {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vienna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 21
        ///68
        ///16.07.2017
        ///Sunday
        ///4:35
        ///20:49
        ///partly cloudy
        ///21
        ///10
        ///NW
        ///7.2
        ///17.07.2017
        ///Monday
        ///4:36
        ///20:48
        ///cloudy
        ///20
        ///15
        ///W
        ///14.4
        ///18.07.2017
        ///Tuesday
        ///4:37
        ///20:47
        ///prevailingly cloudy
        ///21
        ///11
        ///W
        ///7.2
        ///19.07.2017
        ///Wednesday
        ///4:38
        ///20:46
        ///mostly clear
        ///25
        ///11
        ///SE
        ///3.6
        ///20.07.2017
        ///Thursday
        ///4:40
        ///20:44
        ///mostly clear
        ///29
        ///15
        ///SE
        ///3.6
        ///Vilnius.
        /// </summary>
        internal static string Get_Data_For_App_Vilnius {
            get {
                return ResourceManager.GetString("Get_Data_For_App_Vilnius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hail_day_night {
            get {
                object obj = ResourceManager.GetObject("hail_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap haze_day_night {
            get {
                object obj = ResourceManager.GetObject("haze_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heavy_rain_day_night {
            get {
                object obj = ResourceManager.GetObject("heavy_rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap heavy_snow_day_night {
            get {
                object obj = ResourceManager.GetObject("heavy_snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hurricane_day_night {
            get {
                object obj = ResourceManager.GetObject("hurricane_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap i {
            get {
                object obj = ResourceManager.GetObject("i", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onboarding_partlycloudy {
            get {
                object obj = ResourceManager.GetObject("onboarding_partlycloudy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap onboarding_rain {
            get {
                object obj = ResourceManager.GetObject("onboarding_rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap partly_cloudy_day {
            get {
                object obj = ResourceManager.GetObject("partly_cloudy_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_d {
            get {
                object obj = ResourceManager.GetObject("rain_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_day_night {
            get {
                object obj = ResourceManager.GetObject("rain_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_0 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_10 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_100 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_100", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_20 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_30 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_30", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_40 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_40", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_50 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_50", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_60 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_60", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_70 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_70", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_80 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_80", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_ico_90 {
            get {
                object obj = ResourceManager.GetObject("rain_ico_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain_n {
            get {
                object obj = ResourceManager.GetObject("rain_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scattered_showers_day_night {
            get {
                object obj = ResourceManager.GetObject("scattered_showers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scattered_thunderstorms_night {
            get {
                object obj = ResourceManager.GetObject("scattered_thunderstorms_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap scatttered_thundershowers_day {
            get {
                object obj = ResourceManager.GetObject("scatttered_thundershowers_day", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleet_day_night {
            get {
                object obj = ResourceManager.GetObject("sleet_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sleet_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("sleet_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smoky_day_night {
            get {
                object obj = ResourceManager.GetObject("smoky_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_d {
            get {
                object obj = ResourceManager.GetObject("snow_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_day_night {
            get {
                object obj = ResourceManager.GetObject("snow_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_n {
            get {
                object obj = ResourceManager.GetObject("snow_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap snow_rain_mix_day_night {
            get {
                object obj = ResourceManager.GetObject("snow_rain_mix_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_d {
            get {
                object obj = ResourceManager.GetObject("storm_d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storm_n {
            get {
                object obj = ResourceManager.GetObject("storm_n", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thundershowers_day_night {
            get {
                object obj = ResourceManager.GetObject("thundershowers_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thunderstorm_day_night {
            get {
                object obj = ResourceManager.GetObject("thunderstorm_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tornado_day_night {
            get {
                object obj = ResourceManager.GetObject("tornado_day_night", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowicons {
            get {
                object obj = ResourceManager.GetObject("windowicons", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap x {
            get {
                object obj = ResourceManager.GetObject("x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
