//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magazin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MagazinDatabaseEntities : DbContext
    {
        public MagazinDatabaseEntities()
            : base("name=MagazinDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Angajati> Angajati { get; set; }
        public DbSet<Clienti> Clienti { get; set; }
        public DbSet<Produse> Produse { get; set; }
        public DbSet<Vanzari> Vanzari { get; set; }
    }
}
